### ISSUE TITLE
Config typo?

### ISSUE THREAD

**Issue by aptonline** [mitchellrj/eufy_robovac#15]
While setting up the Home Assistant integration if I place the `eufy_robovac` folder in the custom components folder and add the following code (as shown on the install instructions Home Assistant shows a config valuation error:

```
eufy_vacuum:
  devices:
  - name: Robovac
    address: 192.168.1.80
    access_token: YOUR LOCAL KEY HERE
    id: YOUR DEVICE ID HERE
    type: T2118
```

If I change `eufy_vacuum` to `eufy_robovac` (the same name as the custom_components folder) its shows as valid.  I'm using HA 0.110.4.

I still can't get my RoboVac 15C Max to appear however but this may be down to being unsupported or is there indeed a config issue?
