### ISSUE TITLE
Component error: eufy_vacuum - Integration 'eufy_vacuum' not found.

### ISSUE THREAD

**Issue by Lawrencezarb** [mitchellrj/eufy_robovac#29]
Am I missing something, but I cannot get Home assistant to recognise the component. I copied all the files as per the instruction but the above error when validating the config keeps popping up

**Comment by 3ative** [comment]
@Lawrencezarb 
Why is this closed, did you find a fix?
 - I have the same issue today, after an HA update

**Comment by WhimsySpoon** [comment]
The manifest.json needs a version. Adding it to mine made it work again.

**Comment by 3ative** [comment]
@WhimsySpoon Thanks for your reply... But, I have no idea what that means or where "manifest.json" is. 
Can you shed anymore light on it? 
Thanks.

**Comment by WhimsySpoon** [comment]
My apologies, my previous message wasn't very clear. The current version of HA demands a version key present in the `manifest.json` for the custom_component or it will refuse to load it. Details here: https://developers.home-assistant.io/docs/creating_integration_manifest/

This custom component doesn't have the `manifest.json` present, let alone the `version` property, hence HA is now ignoring it completely.

To get it working on my instance, I created a `manifest.json` file in `\config\custom_components\eufy_vacuum` and populated it with the following:

```
{
  "domain": "eufy_vacuum",
  "name": "Eufy Vacuum",
  "documentation": "",
  "issue_tracker": "",
  "dependencies": [],
  "codeowners": [],
  "requirements": [],
  "version": "0.9"
}
```

Once you've created the file, restart HA and you should be good to go. If it works for you too, I can get a PR raised to include it in the repo.

**Comment by 3ative** [comment]
@WhimsySpoon 
No worries, I kinda knew about the manifest file by looking at other integrations. 
I was close, I made one containing this:
```yaml
{
  "domain": "eufy_vacuum",
  "name": "Eufy Vacuum",
  "config_flow": true,
  "documentation": "https://github.com/mitchellrj/eufy_robovac",
  "issue_tracker": "https://github.com/mitchellrj/eufy_robovac/issues",
  "requirements": [],
  "ssdp": [],
  "zeroconf": [],
  "homekit": {},
  "dependencies": [],
  "codeowners": [
    "@mitchellrj"
  ],
  "version": "028"
}
```

> I was trying different version numbers, as I couldn't find it on the GitHub page. 🤣

**Steps needed here were:**
1. Remove it out of configuration.yaml
2. Re-Start HA
3. Copy folder back in
4. **Add in your manifest.json**
4. Re-Start HA
5. Put the entry back in configuration.yaml
6. Re-Start HA

And YAY, _I can confirm it's working again._ I prolly didn't need all those steps, but... 😎

❤**Thank you | Thank You | Thank You!! for replying and sharing.** ❤
