### ISSUE TITLE
failed: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by kieronbos** [mitchellrj/eufy_robovac#9]
Hi, getting the following:

`Connection to [devId] (192.168.0.14:6668) failed: [Errno 104] Connection reset by peer`

Using a 30C, on `current wifi version 1.1.3` and `MCU version 1.1.4`

I can see this on the dash: https://gyazo.com/7797d189e49bc3c1e64c05d77bb381aa

My config is:

```
eufy_vacuum:
  devices:
  - name: Robovac
    address: 192.168.0.14
    access_token: [localKey from logs]
    id: [devId from logs]
    type: T2118
```

Thanks in advance if anyone can help.

Edit; somehow, I **was** just then able to toggle the vacuum on and off via the dash, but have not since been able too, logs still showing the above ^

Another edit; seems ok now! perhaps the error is like a spam error, and it was blocking me or something, I left it in case it needed to rest from me testing it every 4 seconds, and seems great now!
